[package]
name = "proofofwork"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
data-encoding = "2.3.2"
num-bigint = "0.4.3"
ring = "0.16.20"
